export const FLAGGED_ERROR_CODES = Object.freeze({
  NO_PERSON_FOUND: "NO_PERSON_FOUND",
  MORE_THAN_ONE_PERSON: "MORE_THAN_ONE_PERSON",
  ONLY_FEMALE_ALLOWED_IN_IMAGE: `ONLY_FEMALE_ALLOWED_IN_IMAGE`,
  NSFW_IMAGE: `NSFW_IMAGE`,

  UNKNOWN_ERROR: "UNKNOWN_ERROR",
});
